name: Update inbox.json every 5 min

on:
  workflow_dispatch:

jobs:
  update-inbox:
    runs-on: ubuntu-latest

    env:
      CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Gmail fetch script
        run: node index.js

      - name: Commit and push inbox.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add inbox.json
          git commit -m "auto: update inbox.json" || echo "No changes to commit"
          git push
